### ISSUE TITLE
Anon access does not work

### ISSUE THREAD

**Issue by drahnr** [mbr/container_registry-rs#3]
The current code always requires a `_auth: ValidUser`, even if the auth check is disabled, using `Box::new(true)`.

**Comment by marc-gensyn** [comment]
`true` (`:bool`) does not disable the auth, it just says that any auth is accepted valid. I have not looked into how true anonymous access works, would probably require extending the trait here. With this, we. could implement auth for `()`.

**Comment by marc-gensyn** [comment]
Fixed in the latest release (`0.2.0`).
